language: ruby
cache: bundler
dist: trusty
sudo: required

rvm:
- 2.3.7
- 2.4.4
- 2.5.1

before_install:
  - git fetch --tags
  - sudo apt-get update
  - sudo apt-get install python
  - nvm install node
  - nvm use node
  - gem install bundler:1.16.3

install:
  - pip install --user bumpversion
  - npm install -g semantic-release
  - npm install -g @semantic-release/exec
  - npm install -g @semantic-release/git
  - bundle _1.16.3_ install
script:
- bundle exec rake

before_deploy:
  - bundle exec rake test:appveyor_status

deploy:
  - provider: script
    script: npx semantic-release
    on:
      branch: master
      rvm: 2.5.1

  - provider: rubygems
    api_key: $RUBYGEMS_API_KEY
    gem: ibm_watson
    on:
      branch: master
      rvm: 2.5.1

matrix:
  fast_finish: true

notifications:
  email: false
