version: 1.0.{build}-{branch}
skip_tags: true

cache:
  - vendor/bundle

environment:
  matrix:
    - RUBY_VERSION: 23-x64
    - RUBY_VERSION: 24-x64
    - RUBY_VERSION: 25-x64

init:
  - set PATH=C:\Ruby%RUBY_VERSION%\bin;%PATH%

install:
  - ps: |
      if ($Env:RUBY_VERSION -match "^23" ) {
        # RubyInstaller; download OpenSSL headers from OpenKnapsack Project
        $Env:openssl_dir = "C:\Ruby${Env:RUBY_VERSION}"
        appveyor DownloadFile http://dl.bintray.com/oneclick/OpenKnapsack/x64/openssl-1.0.2j-x64-windows.tar.lzma
        7z e openssl-1.0.2j-x64-windows.tar.lzma
        7z x -y -oC:\Ruby${Env:RUBY_VERSION} openssl-1.0.2j-x64-windows.tar
      } else {
        # RubyInstaller2; openssl package seems to be installed already
        $Env:openssl_dir = "C:\msys64\mingw64"
      }
  - set SSL_CERT_FILE=C:/ruby24-x64/ssl/cert.pem
  - gem install bundler:1.16.3
  - bundle _1.16.3_ install
  - gem uninstall -a -x --force eventmachine
  - gem install eventmachine --platform ruby --no-document -- --with-ssl-dir=%openssl_dir%

build: off

before_test:
  - ruby -v
  - gem -v
  - bundle -v

test_script:
  - bundle exec rake

deploy: off
matrix:
  fast_finish: true
